MERGED BRANCH onet4
git-svn-id: https://godirepo.camlcity.org/svn/lib-ocamlnet2/trunk@2195 96e5b9e0-aa12-0410-9e2e-b23d24e56262

diff --git a/code/configure b/code/configure
--- a/code/configure
+++ b/code/configure
@@ -46,30 +46,34 @@ set_defaults () {
     enable_gtk=0
     enable_gtk2=0
     enable_tcl=0
-    enable_ssl=0
     enable_zip=0
-    enable_crypto=0
     enable_apache=0
+    enable_gnutls=0
+    enable_gssapi=0
     enable_pcre=0
     enable_full_pcre=0
     compat_pcre=0
-    with_nethttpd=0
-    with_rpc_auth_dh=0
+    enable_nethttpd=0
     bindir=`dirname "$ocamlc"`
     tcl_defs=""
     tcl_libs=""
-    adh_style=""
     disable_core=0
     apxs=""
     apache=""
     cpp=cpp
     cpp_set=0
+    gnutls_cflags=""
+    gnutls_libs=""
+    gnutls_system_trust_file=""
+    gssapi_cflags=""
+    gssapi_libs=""
+    destdir=""
 }
 
 ocamlc=`get_path ocamlc`
 set_defaults
 
-version="3.7.7"
+version="4.0.0rc1"
 exec_suffix=""
 path_sep=":"
 
@@ -79,18 +83,16 @@ path_sep=":"
 ehelp_gtk="Enable/disable parts that depend on lablgtk"
 ehelp_gtk2="Enable/disable parts that depend on lablgtk2"
 ehelp_tcl="Enable/disable parts that depend on tcl/tk"
-ehelp_ssl="Enable/disable parts that depend on SSL"
+ehelp_gnutls="Enable/disable parts that depend on GnuTLS"
+ehelp_gssapi="Enable/disable parts that depend on GSSAPI/Kerberos"
 ehelp_zip="Enable/disable parts that depend on camlzip"
-ehelp_crypto="Enable/disable parts that depend on cryptokit"
 ehelp_apache="Enable/disable Apache mod connector (EXPERIMENTAL)"
 ehelp_pcre="Enable/disable the build against pcre-ocaml"
 ehelp_full_pcre="Enable/disable the build against pcre-ocaml (no Str)"
-whelp_nethttpd="Enable/disable nethttpd web server component (GPL!)"
-whelp_rpc_auth_dh="Enable/disable support for SecureRPC (Diffie-Hellman auth)"
+ehelp_nethttpd="Enable/disable nethttpd web server component (GPL!)"
 
-# Which options exist? eoptions for enable/disable, woptions for with/without:
-eoptions="pcre full_pcre gtk gtk2 tcl ssl zip crypto apache"
-woptions="nethttpd rpc_auth_dh"
+# Which options exist? eoptions for enable/disable
+eoptions="pcre full_pcre gtk gtk2 tcl gnutls gssapi zip apache nethttpd"
 
 # Packages to include anyway:
 requires="unix"
@@ -132,26 +134,11 @@ print_options () {
 			echo "    -disable-$uopt"
 		fi
 	done
-	for opt in $woptions; do
-		e="o=\$with_$opt"
-		eval "$e"
-		uopt=`echo $opt | sed -e 's/_/-/g'`
-		if [ $o -gt 0 ]; then
-			echo "    -with-$uopt"
-		else
-			echo "    -without-$uopt"
-		fi
-	done
 	echo "    -bindir $bindir"
 	echo "    -datadir $net_db_dir"
 	if [ $enable_tcl -gt 0 ]; then
             echo "    -equeue-tcl-defs \"$tcl_defs\""
             echo "    -equeue-tcl-libs \"$tcl_libs\""
-	fi
-	if [ $with_rpc_auth_dh -gt 0 ]; then
-	    if [ -n "$adh_style" ]; then
-		echo "    -auth-dh-style $adh_style"
-	    fi
 	fi
 	if [ -n "$apxs" ]; then
 	    echo "    -apxs $apxs"
@@ -159,6 +146,21 @@ print_options () {
 	if [ -n "$apache" ]; then
 	    echo "    -apache $apache"
 	fi
+        if [ -n "$gnutls_cflags" ]; then
+            echo "    -gnutls-cflags $gnutls_cflags"
+        fi
+        if [ -n "$gnutls_libs" ]; then
+            echo "    -gnutls-libs $gnutls_libs"
+        fi
+        if [ -n "$gnutls_system_trust_file" ]; then
+            echo "    -gnutls-system-trust-file $gnutls_system_trust_file"
+        fi
+        if [ -n "$gssapi_cflags" ]; then
+            echo "    -gssapi-cflags $gssapi_cflags"
+        fi
+        if [ -n "$gssapi_libs" ]; then
+            echo "    -gssapi-libs $gssapi_libs"
+        fi
         echo "    -cpp $cpp"
 }
 
@@ -177,14 +179,6 @@ _EOF_
 		echo "-disable-$uopt:" >&2
 		echo "        $help" >&2
 	done
-	for opt in $woptions; do
-		e="help=\$whelp_$opt"
-		eval "$e"
-		uopt=`echo $opt | sed -e 's/_/-/g'`
-		echo "-with-$uopt:" >&2
-		echo "-without-$uopt:" >&2
-		echo "        $help" >&2
-	done
 	cat <<_EOF_ >&2
 -bindir dir
         Install binaries into this directory
@@ -198,14 +192,26 @@ _EOF_
 -equeue-tcl-libs <opts>
         Set C compiler options to link against libtcl (for -enable-tcl)
 
--auth-dh-style (keyenvoy|unixdomain|tirpc)
-        Set style of keyserv connector (see README.authdh)
-
 -apxs /path/to/apxs
         Set which apxs to use for -enable-apache
 
 -apache /path/to/apache
         Set which apache executable to use for -enable-apache
+
+-gnutls-cflags <opts>
+        Flags for the C compiler for GnuTLS
+
+-gnutls-libs <opts>
+        Libraries for GnuTLS
+
+-gnutls-system-trust-file /path/to/certificates.crt
+        File with the certificates that are trusted by default
+
+-gssapi-cflags <opts>
+        Flags for the C compiler for GSSAPI
+
+-gssapi-libs <opts>
+        Libraries for GSSAPI
 
 -prefer-netcgi2
         This option is ignored for compatibility with older versions
@@ -236,101 +242,168 @@ check_eopt () {
 }
 
 
-check_wopt () {
-	for x in $woptions; do
-		if [ "$x" = "$1" ]; then
-			return 0
-		fi
-	done
-	echo "Unknown option: $1" >&2
-	exit 1
-}
-
-
 echo "Welcome to Ocamlnet version $version" >&2
 
 while [ "$#" -gt 0 ]; do
 	case "$1" in
-		-enable-*)
-			opt=`echo "$1" | sed -e 's/-enable-//' -e 's/-/_/g'`
+		-enable-*|--enable-*)
+			opt=`echo "$1" | sed -e 's/--\{0,1\}enable-//' -e 's/-/_/g'`
 			check_eopt "$opt"
 			eval "enable_$opt=2"
 			shift
 			;;
-	        -disable-core)
+	        -disable-core|--disable-core)
 		        # Intentionally undocumented.
 		        disable_core=1
 			shift
 			;;
-		-disable-*)
-			opt=`echo "$1" | sed -e 's/-disable-//' -e 's/-/_/g'`
+		-disable-*|--disable-*)
+			opt=`echo "$1" | sed -e 's/--\{0,1\}disable-//' -e 's/-/_/g'`
 			check_eopt "$opt"
 			eval "enable_$opt=-1"
 			shift
 			;;
-		-with-*)
-			opt=`echo "$1" | sed -e 's/-with-//' -e 's/-/_/g'`
-			check_wopt "$opt"
-			eval "with_$opt=2"
+		-with-*|--with*)
+			opt=`echo "$1" | sed -e 's/--\{0,1\}with-//' -e 's/-/_/g'`
+			check_eopt "$opt"
+			eval "enable_$opt=2"
 			shift
 			;;
-		-without-*)
-			opt=`echo "$1" | sed -e 's/-without-//' -e 's/-/_/g'`
-			check_wopt "$opt"
-			eval "with_$opt=-1"
+		-without-*|--without*)
+			opt=`echo "$1" | sed -e 's/--\{0,1\}without-//' -e 's/-/_/g'`
+			check_eopt "$opt"
+			eval "enable_$opt=-1"
 			shift
 			;;
-                -bindir)
+                -prefix|--prefix)
+                        bindir="$2/bin"; shift 2 ;;
+                --prefix=*)
+                        p=`echo "$1" | set -e 's/--prefix=//'`
+                        bindir="$p/bin"; shift ;;
+                -bindir|--bindir)
                         bindir="$2"
                         shift
                         shift
                         ;;
-	        -datadir)
+                --bindir=*)
+                        bindir=`echo "$1" | set -e 's/--bindir=//'`
+                        shift
+                        ;;
+	        -datadir|--datadir)
 		        net_db_dir="$2"
 			net_db_dir_set=1
 			shift; shift
 			;;
-                -equeue-tcl-defs)
+	        --datadir=*)
+		        net_db_dir=`echo "$1" | set -e 's/--datadir=//'`
+			net_db_dir_set=1
+			shift
+			;;
+                -equeue-tcl-defs|--equeue-tcl-defs)
                         tcl_defs="$tcl_defs $2"
                         shift
                         shift
                         ;;
-                -equeue-tcl-libs)
+                --equeue-tcl-defs=*)
+                        tcl_defs=`echo "$1" | set -e 's/--equeue-tcl-defs=//'`" $2"
+                        shift
+                        ;;
+                -equeue-tcl-libs|--equeue-tcl-libs)
                         tcl_libs="$tcl_libs $2"
                         shift
                         shift
                         ;;
-                -auth-dh-style)
-                        adh_style="$2"
-                        shift
+                --equeue-tcl-libs=*)
+                        tcl_libs=`echo "$1" | set -e 's/--equeue-tcl-libs=//'`" $2"
                         shift
                         ;;
-                -apxs)
+                -apxs|--apxs)
                         apxs="$2"
                         shift
                         shift
                         ;;
-                -apache)
+                --apxs=*)
+                        apxs=`echo "$1" | set -e 's/--apxs=//'`
+                        shift
+                        ;;
+                -apache|--apache)
                         apache="$2"
                         shift
                         shift
                         ;;
-	        -prefer-netcgi2)
+                --apache=*)
+                        apache=`echo "$1" | set -e 's/--apache=//'`
+                        shift
+                        ;;
+                -gnutls-cflags|--gnutls-cflags)
+                        gnutls_cflags="$2"
+                        shift
+                        shift
+                        ;;
+                --gnutls-cflags=*)
+                        gnutls_cflags=`echo "$1" | set -e 's/--gnutls-cflags=//'`
+                        shift
+                        ;;
+                -gnutls-libs|--gnutls-libs)
+                        gnutls_libs="$2"
+                        shift
+                        shift
+                        ;;
+                --gnutls-libs=*)
+                        gnutls_libs=`echo "$1" | set -e 's/--gnutls-libs=//'`
+                        shift
+                        ;;
+                -gnutls-system-trust-file|--gnutls-system-trust-file)
+                        gnutls_system_trust_file="$2"
+                        shift 2
+                        ;;
+                --gnutls-system-trust-file=*)
+                        gnutls_system_trust_file=`echo "$1" | set -e 's/--gnutls-system-trust-file=//'`
+                        shift
+                        ;;
+                -gssapi-cflags|--gssapi-cflags)
+                        gssapi_cflags="$2"
+                        shift
+                        shift
+                        ;;
+                --gssapi-cflags=*)
+                        gssapi_cflags=`echo "$1" | set -e 's/--gssapi-cflags=//'`
+                        shift
+                        ;;
+                -gssapi-libs|--gssapi-libs)
+                        gssapi_libs="$2"
+                        shift
+                        shift
+                        ;;
+                --gssapi-libs=*)
+                        gssapi_libs=`echo "$1" | set -e 's/--gssapi-libs=//'`
+                        shift
+                        ;;
+	        -prefer-netcgi2|--prefer-netcgi2)
 		        # ignore!
 			shift ;;
-                -cpp)
+                -cpp|--cpp)
                         cpp="$2"
                         cpp_set=1
                         shift
                         shift
                         ;;
-		-version)
+                --cpp=*)
+                        cpp=`echo "$1" | set -e 's/--cpp=//'`
+                        cpp_set=1
+                        shift
+                        ;;
+		-version|--version)
 			echo "$version"
 			exit 0
 			;;
-                -compat-pcre)
+                -compat-pcre|--compat-pcre)
                         compat_pcre=1
                         shift ;;
+                -destdir|--destdir)
+                        destdir="$2"; shift 2;;
+                --destdir=*)
+                        destdir=`echo "$1" | set -e 's/--destdir=//'`; shift;;
 		*)
 			usage
 	esac
@@ -370,11 +443,9 @@ case "$u" in
 		;;
         Linux)
 	        echo "Linux"
-		[ -n "$adh_style" ] || adh_style=unixdomain
 		;;
         *FreeBSD)             # also GNU/kFreeBSD
 	        echo "FreeBSD"
-		[ -n "$adh_style" ] || adh_style=unixdomain
 		echo
 		echo "*** Note that you might need to load the 'sem' kernel"
 		echo "*** module to make semaphores work: kldload sem"
@@ -382,7 +453,6 @@ case "$u" in
 		;;
         NetBSD)
 	        echo "NetBSD"
-		[ -n "$adh_style" ] || adh_style=unixdomain
 		;;
         SunOS)
 	        case `uname -r` in
@@ -391,7 +461,6 @@ case "$u" in
 		    *)
 			echo "Solaris"
 			with_rpc_xti=1
-			[ -n "$adh_style" ] || adh_style=tirpc
 			;;
 		esac ;;
 	*)
@@ -410,7 +479,7 @@ printf "%s" "Checking for findlib... "
 if ocamlfind query stdlib >/dev/null 2>/dev/null; then
     echo "found"
     if [ "$net_db_dir_set" -eq 0 ]; then
-	net_db_dir=`ocamlfind printconf destdir | tr -d '\\r'`/netstring
+	net_db_dir=`ocamlfind printconf destdir | tr -d '\\r'`/netunidata
 	net_db_dir_set=1
     fi
 else
@@ -746,27 +815,40 @@ EOF
 fi
 
 ######################################################################
-# Check SSL
+# GnuTLS
 
-with_equeue_ssl=0
-with_rpc_ssl=0
+with_gnutls=0
 
-if [ $enable_ssl -gt 0 ]; then
-    printf "%s" "Checking for ssl... "
-    if ocamlfind query ssl >/dev/null 2>/dev/null; then
-	ssl_v=`ocamlfind query -format '%v' ssl`
-	case "$ssl_v" in
-	    0.1*|0.2*|0.3*)
-		echo "found, but too old. Please upgrade ocaml-ssl to at least version 0.4"
-		exit 1 ;;
-	esac
-        echo "found"
-	with_equeue_ssl=1
-	with_rpc_ssl=1
+if [ $enable_gnutls -gt 0 ]; then
+    ( cd src/nettls-gnutls
+      GNUTLS_CFLAGS="$gnutls_cflags" GNUTLS_LIBS="$gnutls_libs" GNUTLS_SYSTEM_TRUST_FILE="$gnutls_system_trust_file" ./configure
+    )
+    if [ $? -eq 0 ]; then
+        with_gnutls=1
+        # There is now also src/nettls-gnutls/config.mk, which needs to be
+        # appended to Makefile.conf
     else
-        echo "not found"
-	echo "Required library ssl not found!"
-	exit 1
+        echo "Required library GnuTLS not found!"
+        exit 1
+    fi
+fi
+
+######################################################################
+# GSSAPI
+
+with_gssapi=0
+
+if [ $enable_gssapi -gt 0 ]; then
+    ( cd src/netgss-system
+      GSSAPI_CFLAGS="$gssapi_cflags" GSSAPI_LIBS="$gssapi_libs" ./configure
+    )
+    if [ $? -eq 0 ]; then
+        with_gssapi=1
+        # There is now also src/netgss-system/config.mk, which needs to be
+        # appended to Makefile.conf
+    else
+        echo "Required library for GSSAPI (probably -lkrb5) not found!"
+        exit 1
     fi
 fi
 
@@ -792,56 +874,6 @@ if [ $enable_zip -gt 0 ]; then
 	    exit 1
         fi
     fi
-fi
-
-######################################################################
-# Check cryptokit
-
-with_crypto=0
-
-if [ $enable_crypto -gt 0 ]; then
-    printf "%s" "Checking for cryptokit... "
-    if ocamlfind query cryptokit >/dev/null 2>/dev/null; then
-        echo "found"
-	with_crypto=1
-    else
-        echo "not found"
-	echo "Required library cryptokit not found!"
-	exit 1
-    fi
-fi
-
-######################################################################
-# Check SecureRPC
-
-adh_reqs=""
-
-if [ $with_rpc_auth_dh -gt 0 ]; then
-    echo  "Checking SecureRPC"
-    printf "    %s" "Checking for cryptgps... "
-    if ocamlfind query cryptgps >/dev/null 2>/dev/null; then
-        echo "found"
-    else
-        echo "not found"
-	echo "Required library cryptgps not found!"
-	exit 1
-    fi
-
-    if [ -z "$adh_style" ]; then
-	echo "    No -auth-dh-style passed and no OS default known. Falling back to keyenvoy"
-	adh_style="keyenvoy"
-    fi
-
-    if [ "$adh_style" = "tirpc" ]; then
-	if [ $with_rpc_xti -eq 0 ]; then
-	    echo "-auth-dh-style tirpc needs rpc-xti which is missing"
-	    exit 1
-	fi
-	adh_reqs=",rpc-xti"  # This is for META.in, hence the comma
-	adh_style="Rpc_xti_client.keyserv"
-    fi
-
-    echo "    SecureRPC is supported"
 fi
 
 ######################################################################
@@ -917,9 +949,9 @@ echo "Effective options:"
 print_options
 echo
 
-pkglist="netsys netshm netstring equeue shell netgssapi rpc-generator rpc rpc-auth-local pop smtp netclient netcgi2 netplex netcgi2-plex"
+pkglist="netsys netshm netstring netunidata equeue shell rpc-generator rpc rpc-auth-local netclient netcgi2 netplex netcgi2-plex"
 
-full_pkglist="$pkglist netstring-pcre rpc-auth-local rpc-xti equeue-tcl equeue-gtk1 equeue-gtk2 equeue-ssl rpc-ssl rpc-auth-dh nethttpd nethttpd-for-netcgi2 netzip netcgi2-apache netmech-scram"
+full_pkglist="$pkglist netstring-pcre rpc-auth-local rpc-xti equeue-tcl equeue-gtk1 equeue-gtk2 nethttpd netzip netcgi2-apache nettls-gnutls netgss-system"
 
 if [ $enable_camlbox -gt 0 ]; then
     pkglist="$pkglist netcamlbox"
@@ -929,13 +961,17 @@ if [ $enable_multicore -gt 0 ]; then
     pkglist="$pkglist netmulticore"
 fi
 
+if [ $enable_nethttpd -gt 0 ]; then
+    pkglist="$pkglist nethttpd"
+fi
+
 if [ $disable_core -gt 0 ]; then
     # Omit the core packages:
     pkglist=""
     with_rpc_xti=0
 fi
 
-for opt in rpc_xti $woptions equeue_tcl equeue_gtk1 equeue_gtk2 equeue_ssl rpc_ssl netzip; do
+for opt in rpc_xti $woptions equeue_tcl equeue_gtk1 equeue_gtk2 netzip; do
 	e="o=\$with_$opt"
 	eval "$e"
 	if [ $o -gt 0 ]; then
@@ -952,16 +988,13 @@ if [ $enable_apache -gt 0 ]; then
     pkglist="$pkglist netcgi2-apache"
 fi
 
-if [ $with_crypto -gt 0 ]; then
-    pkglist="$pkglist netmech-scram"
+if [ $enable_gnutls -gt 0 ]; then
+    pkglist="$pkglist nettls-gnutls"
 fi
 
-if [ $with_nethttpd -gt 0 ]; then
-    # Fixup: nethttpd is already added by the for loop, but we need also
-    # nethttpd-for-netcgi2
-    pkglist="$pkglist nethttpd-for-netcgi2"
+if [ $enable_gssapi -gt 0 ]; then
+    pkglist="$pkglist netgss-system"
 fi
-
 
 ######################################################################
 # Write Makefile.conf
@@ -1050,10 +1083,6 @@ EQUEUE_TCL_LIBS = $tcl_libs
 # For -enable-gtk2:
 GTK_EXTRA_DEFINES = $gtk2_io_add_watch_supports_lists
 
-# For -with-auth-dh:
-RPC_AUTH_DH_CONNECTOR = $adh_style
-AUTHDHREQS = $adh_reqs
-
 # For -enable-apache
 APACHE_MAJOR = $apache_major
 APACHE_LIBDIR = $apache_libdir
@@ -1074,6 +1103,25 @@ CPPO = $cppo
 CPPO_VERSION = $cppo_version
 $export_path
 _EOF_
+
+if [ $with_gnutls -gt 0 ]; then
+    cat src/nettls-gnutls/config.mk >>Makefile.conf
+fi
+
+if [ $with_gssapi -gt 0 ]; then
+    cat src/netgss-system/config.mk >>Makefile.conf
+fi
+
+if [ -n "$destdir" ]; then
+    echo "DESTDIR = $destdir" >>Makefile.conf
+fi
+
+rm -f src/netcgi2-apache/config.h
+
+######################################################################
+# make oasis happy
+
+touch setup.data
 
 ######################################################################
 # Finish
